/*
 * ─────────────────────────────────────────────────────────────────────────────
 * HUMAN-READABLE CODE SEQUENCES — BUG-011, Task 4.9, DECISIONS.md D-050
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * Seven code series were generated by `count(*) + 1` at three independent call
 * sites (`customers.routes.ts`, `scoped-resource.ts`, `imports.routes.ts`). A
 * count goes DOWN on a permanent delete, so the next create is handed a number
 * already used, and two concurrent creates read the same count. One sequence
 * per prefix replaces all three: lock-free, monotonic, never re-issued.
 *
 * ⚠️ These sequences are the ONLY generator. Nothing may fall back to a count.
 *
 * ── Why `setval` and not `START WITH` ──────────────────────────────────────
 * drizzle-kit cannot generate this file: the starting value is data-dependent.
 * Each sequence is initialised from the HIGHEST NUMBER EVER ISSUED for its
 * prefix, which is read from three places, exactly as D-032 established for
 * `nextEmployeeCode`:
 *
 *   1. live rows                      — codes currently in use;
 *   2. soft-deleted rows              — `deleted_at IS NOT NULL` rows are NOT
 *      filtered out. That absence is load-bearing correctness, not an
 *      oversight: `customers_code_unique` is PARTIAL (`WHERE deleted_at is
 *      null`, 0000_init.sql:286), so re-issuing a soft-deleted row's code would
 *      be accepted by the index and would make restoring that row from the
 *      recycle bin permanently impossible (PRD R3.1 AC3). For `ledger_entries`
 *      and `transactions` the index is UNCONDITIONAL (0002_operations.sql:325,
 *      :345), so it would be an immediate 23505 instead;
 *   3. retained recycle-bin snapshots — a PERMANENT delete removes the row
 *      entirely, so the table alone cannot remember the number.
 *      `permanentDelete` keeps the bin entry and only stamps `purged_at`
 *      (services/recycle-bin.ts:245-279), and the snapshot is the whole row, so
 *      `snapshot->>'code'` is the one source that survives a purge. Keys are
 *      the camelCase drizzle property names, hence `'code'`, not `'CODE'`.
 *
 * `setval(seq, n, true)` means "n has been used", so the next `nextval` returns
 * n + 1. Seeded with GREATEST(codeStart, ...max ever issued...), an empty table
 * therefore yields codeStart + 1 — CUS-10001, LN-1001, BO-2401, DSB-5001,
 * STL-3301, TXN-77001, LG-9001 — which is EXACTLY what `codeStart + count + 1`
 * produced on an empty table. The existing series continues; nothing renumbers.
 *
 * Non-conforming codes (`CONTRACT-77`, a hand-entered `LN-A12`) do not match the
 * anchored pattern, contribute NULL to `max()`, and are ignored — the same
 * property `nextEmployeeCode` relies on.
 *
 * Known and accepted gap: a code on a row hard-deleted WITHOUT passing through
 * the recycle bin is unrecoverable here. No route does that — `customers.bank_id`
 * is `ON DELETE restrict`, so a bank purge cannot cascade customers away — and
 * D-032 accepted the identical limitation for employees.
 *
 * Sequences are transaction-safe and gap-tolerant by design: `nextval` is not
 * rolled back, so an aborted create burns a number. A GAP IS HARMLESS. REUSE IS
 * NOT. That trade is the entire point of this migration.
 */
CREATE SEQUENCE "customer_code_seq" AS bigint;--> statement-breakpoint
SELECT setval('customer_code_seq', GREATEST(
  10000,
  COALESCE((SELECT max(nullif(substring("code" from '^CUS-([0-9]+)$'), '')::bigint) FROM "customers"), 0),
  COALESCE((SELECT max(nullif(substring("snapshot"->>'code' from '^CUS-([0-9]+)$'), '')::bigint)
              FROM "recycle_bin_entries" WHERE "record_type" = 'customer'), 0)
), true);--> statement-breakpoint

CREATE SEQUENCE "loan_code_seq" AS bigint;--> statement-breakpoint
SELECT setval('loan_code_seq', GREATEST(
  1000,
  COALESCE((SELECT max(nullif(substring("code" from '^LN-([0-9]+)$'), '')::bigint) FROM "loans"), 0),
  COALESCE((SELECT max(nullif(substring("snapshot"->>'code' from '^LN-([0-9]+)$'), '')::bigint)
              FROM "recycle_bin_entries" WHERE "record_type" = 'loan'), 0)
), true);--> statement-breakpoint

CREATE SEQUENCE "bank_order_code_seq" AS bigint;--> statement-breakpoint
SELECT setval('bank_order_code_seq', GREATEST(
  2400,
  COALESCE((SELECT max(nullif(substring("code" from '^BO-([0-9]+)$'), '')::bigint) FROM "bank_orders"), 0),
  COALESCE((SELECT max(nullif(substring("snapshot"->>'code' from '^BO-([0-9]+)$'), '')::bigint)
              FROM "recycle_bin_entries" WHERE "record_type" = 'bank_order'), 0)
), true);--> statement-breakpoint

CREATE SEQUENCE "disbursement_code_seq" AS bigint;--> statement-breakpoint
SELECT setval('disbursement_code_seq', GREATEST(
  5000,
  COALESCE((SELECT max(nullif(substring("code" from '^DSB-([0-9]+)$'), '')::bigint) FROM "disbursements"), 0),
  COALESCE((SELECT max(nullif(substring("snapshot"->>'code' from '^DSB-([0-9]+)$'), '')::bigint)
              FROM "recycle_bin_entries" WHERE "record_type" = 'disbursement'), 0)
), true);--> statement-breakpoint

CREATE SEQUENCE "settlement_code_seq" AS bigint;--> statement-breakpoint
SELECT setval('settlement_code_seq', GREATEST(
  3300,
  COALESCE((SELECT max(nullif(substring("code" from '^STL-([0-9]+)$'), '')::bigint) FROM "settlements"), 0),
  COALESCE((SELECT max(nullif(substring("snapshot"->>'code' from '^STL-([0-9]+)$'), '')::bigint)
              FROM "recycle_bin_entries" WHERE "record_type" = 'settlement'), 0)
), true);--> statement-breakpoint

CREATE SEQUENCE "transaction_code_seq" AS bigint;--> statement-breakpoint
SELECT setval('transaction_code_seq', GREATEST(
  77000,
  COALESCE((SELECT max(nullif(substring("code" from '^TXN-([0-9]+)$'), '')::bigint) FROM "transactions"), 0),
  COALESCE((SELECT max(nullif(substring("snapshot"->>'code' from '^TXN-([0-9]+)$'), '')::bigint)
              FROM "recycle_bin_entries" WHERE "record_type" = 'transaction'), 0)
), true);--> statement-breakpoint

CREATE SEQUENCE "ledger_entry_code_seq" AS bigint;--> statement-breakpoint
SELECT setval('ledger_entry_code_seq', GREATEST(
  9000,
  COALESCE((SELECT max(nullif(substring("code" from '^LG-([0-9]+)$'), '')::bigint) FROM "ledger_entries"), 0),
  COALESCE((SELECT max(nullif(substring("snapshot"->>'code' from '^LG-([0-9]+)$'), '')::bigint)
              FROM "recycle_bin_entries" WHERE "record_type" = 'ledger_entry'), 0)
), true);
